DROP TABLE IF EXISTS FRIEND;
DROP TABLE IF EXISTS SESSION;
DROP TABLE IF EXISTS USER_UPDATE;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	ID CHAR(36) NOT NULL PRIMARY KEY UNIQUE,
	EMAIL VARCHAR(320) NOT NULL UNIQUE,
	USERNAME CHAR(20) NOT NULL UNIQUE,
	PASSWORD CHAR(72) NOT NULL,
	LAST_ONLINE_TS INT NOT NULL,
    BIO CHAR(100),
	REGISTERED_TS INT NOT NULL
);

CREATE TABLE SESSION (
    ID CHAR(36) NOT NULL PRIMARY KEY UNIQUE,
    USER_ID CHAR(36) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) 
);

CREATE TABLE FRIEND (
    ID CHAR(36) NOT NULL PRIMARY KEY UNIQUE,
    SENDER_ID CHAR(36) NOT NULL,
    FOREIGN KEY (SENDER_ID) REFERENCES USER(ID),
    RECIPIENT_ID CHAR(36) NOT NULL,
    FOREIGN KEY (RECIPIENT_ID) REFERENCES USER(ID),
    ACCEPTED BOOLEAN NOT NULL,
    ACCEPTED_TS INT,
    SENT_TS INT NOT NULL
);

CREATE TABLE USER_UPDATE (
    ID CHAR(36) NOT NULL PRIMARY KEY UNIQUE,
    USER_ID CHAR(36) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    MSG TEXT NOT NULL,
    TS INT NOT NULL
);
